version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
    build:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run: npm install
        - run: npm test